defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: asymmetric_sinh_minmax_asinh.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "byol-banner-rgz-finetune-minmax"
pretrained_feature_extractor: "./trained_models/byol/ddn5f8w5/byol-norm-aug-ddn5f8w5-ep=275.ckpt"
backbone:
  name: "resnet18"
pretrain_method: "byol"
data:
  dataset: rgz
  train_path: "../RGZ-D1-smorph-dataset"
  val_path: "../RGZ-D1-smorph-dataset"
  format: "image_folder"
  num_workers: 8
optimizer:
  name: "adamw"
  batch_size: 512
  lr: 5e-4
  weight_decay: 0.05
  #layer_decay: 0.75
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.0
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 25
auto_resume:
  enabled: True
label_smoothing: 0.1
finetune: True

# overwrite PL stuff
max_epochs: 100
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
