defaults:
  - _self_
  - augmentations: symmetric_fits.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-banner"
method: "barlow_twins"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 1024
  proj_output_dim: 512
  lamb: 0.0051
  scale_loss: 0.048
data:
  dataset: custom
  train_path: "../Banner-cutout_factor2.5-full/meerkat"
  val_path: "../Banner-cutout_factor2.5-full/meerkat"
  format: "image_folder"
  num_workers: 8
  no_labels: True
optimizer:
  name: "lars"
  batch_size: 254
  lr: 0.8
  classifier_lr: 0.1
  weight_decay: 1.5e-6
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 33
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 331
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
