defaults:
  - _self_
  - augmentations: symmetric_fits.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "deepclusterv2-banner"
method: "deepclusterv2"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  num_prototypes: [3000, 3000, 3000]
data:
  dataset: custom
  train_path: "../Banner-cutout_factor2.5-full/meerkat"
  val_path: "../Banner-cutout_factor2.5-full/meerkat"
  format: "image_folder"
  num_workers: 4
  no_labels: True
optimizer:
  name: "lars"
  batch_size: 254
  lr: 0.6
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
  min_lr: 0.0006
  warmup_start_lr: 0.0
  warmup_epochs: 11
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
dali:
  encode_indexes_into_labels: True

# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
