defaults:
  - _self_
  - augmentations: symmetric_fits.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "swav-banner"
method: "swav"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  queue_size: 3840
  proj_output_dim: 128
  num_prototypes: 3000
  epoch_queue_starts: 50
  freeze_prototypes_epochs: 2
  temperature: 0.1
data:
  dataset: "custom"
  train_path: "../Banner-cutout_factor2.5-full/meerkat"
  val_path: "../Banner-cutout_factor2.5-full/meerkat"  # remove this if there's no validation dir
  format: "image_folder" # data format, supports "image_folder", "dali" or "h5"
  num_workers: 4
  no_labels: True
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.6
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
