defaults:
  - _self_
  - wandb: private.yaml
  - augmentations: asymmetric_sinh_minmax_asinh.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mae-banner-rgz-linear-mixed"
pretrained_feature_extractor: "./trained_models/mae/zo83dj1h/mae-banner-zo83dj1h-ep=330.ckpt"
backbone:
  name: "vit_base"
pretrain_method: "mae"
data:
  dataset: "rgz"
  train_path: "../RGZ-D1-smorph-dataset"
  val_path: "../RGZ-D1-smorph-dataset"
  format: "image_folder"
  num_workers: 8
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [10, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 25
auto_resume:
  enabled: True

performance:
  disable_channel_last: True

# overwrite PL stuff
max_epochs: 100
devices: [0, 1]
sync_batchnorm: True
accelerator: "gpu"
strategy: auto
precision: 16
